##### GENERAL INFO #####
## Name (top of page)
name: Utah Mathematical Olympiad
# name: Utah Math Olympiad # Not sure which is better...
## Short description
description: Utah Math Olympiad Website
## Author (hidden)
author: Caleb Stanford
## email 
author_email: contact@utmath.org
# Alt: caleb at utmath dot org
## Uncomment to run in a subdirectory
# baseurl: /
## URL of the domain
url: http://www.utmath.org

##### NAVIGATION #####
navigation:
 - text: Home
   url: /
 - text: Problems and Solutions
   url: /problems/
 # - text: Registration
 #   url: /registration/
 - text: Results
   url: /results/
 - text: Resources
   url: /resources/
 - text: About Us
   url: /about/
---


##### TECHNICAL #####
## Markdown Engine
# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount
# markdown: maruku
# markdown: kramdown # Works with MathJax
## Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty
## Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
## Google analytics
# TODO
# google_analytics: UA-????????-?

##### DELETE
## The directory for category index pages.
# category_dir: /
## Override the default excerpt behavior by customizing the excerpt separator.
# excerpt_separator: <!--EXCERPT TO HERE-->
